test: bail out if TOKEN empty

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -46,6 +46,8 @@ runs:
             echo "Unable to parse variable $variable"
           fi
         done
+        # Fail when TOKEN empty
+        test -n "${TOKEN}" || echo "Token has zero length" && false
         # Print webhook call
         echo curl -X POST \
              --fail \
